-- Explicit Initial Content Seed for Collections & Studies
-- Can be executed via: npx wrangler d1 execute DB --local --file=./migrations/0002_seed_initial_content.sql

INSERT OR IGNORE INTO collections (id, slug, title, subtitle, description, period, location_context, order_index, created_at, updated_at)
VALUES 
  ('col-archive-arch', 'archive-architecture', 'Archive Architecture', 'Systemic taxonomies, metadata structures, and epistemic permanence', 'An ongoing theoretical and technical investigation into how computational schemas, metadata boundaries, and physical archival practices shape collective memory and cultural retrieval.', '2024 — Present', 'Computational / Los Angeles & Remote', 1, datetime('now'), datetime('now')),
  ('col-european-field', 'european-field-studies', 'European Field Studies', 'Visual ethnography, architectural typologies, and fragmented monuments', 'Field notes, photographic surveys, and topographic tracings across Venice, Rome, Berlin, and Lisbon examining the tension between stone permanence and historical erosion.', '2023 — 2025', 'Venice, Berlin, Rome, Lisbon', 2, datetime('now'), datetime('now')),
  ('col-chinatown-studies', 'chinatown-studies', 'Chinatown Studies', 'Linguistic topography, vernacular signages, and diaspora spatial memory', 'An architectural and linguistic documentation project recording vanishing hand-painted Cantonese signboards, clan association facades, and shifting neighborhood demarcations in North American enclaves.', '2022 — Present', 'Manhattan, San Francisco, Vancouver', 3, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO studies (id, slug, collection_id, title, subtitle, description, archival_date, order_index, created_at, updated_at)
VALUES
  ('std-metadata-labels', 'metadata-labels-taxonomy', 'col-archive-arch', 'Metadata Labels & Rigid Classification', 'On the tension between standardized schemas and erratic artifacts', 'Explorations in constructing fixed semantic headers for fluid, unstandardized human observations. Formulating metadata as an architectural armature rather than a container.', '2025.01.12', 1, datetime('now'), datetime('now')),
  ('std-revision-systems', 'revision-systems-state-changes', 'col-archive-arch', 'Revision Systems & State Changes', 'Intentional artistic versioning vs automatic technical telemetry', 'Distinguishing between deliberate intellectual milestones (REV 00, REV 01) and low-level system timestamp telemetry. Preserving human agency over digital churn.', '2025.04.03', 2, datetime('now'), datetime('now')),
  ('std-stone-typography', 'monuments-decay-stone-typography', 'col-european-field', 'Monuments in Decay & Stone Inscriptions', 'Lapidary letters eroded by moisture and atmospheric particulate', 'A visual index of classical and medieval lapidary inscriptions across central Rome and Roman ruins, documenting the point where chiselled Roman capitals dissolve into lichen.', '2024.09.15', 3, datetime('now'), datetime('now')),
  ('std-venetian-cartography', 'venetian-cartography-fluid-topographies', 'col-european-field', 'Venetian Cartography & Fluid Topographies', 'Tidal thresholds, canal borders, and the Barbari 1500 woodcut', 'Tracing Jacopo de’ Barbari’s monumental 1500 aerial woodcut against modern tidal water levels in the lagoon. Field notes on the disappearance of Istrian stone steps.', '2024.11.02', 4, datetime('now'), datetime('now')),
  ('std-vernacular-signs', 'vernacular-typography-diaspora-signs', 'col-chinatown-studies', 'Vernacular Typography & Diaspora Signs', 'Gold-leaf calligraphy, neon overhangs, and dual-script facades', 'Field photography, rubbings, and typographic traces of bilingual storefronts along Mott, Pell, and Grant Avenue. Analyzing the hybridization of brushwork with industrial metalwork.', '2024.02.18', 5, datetime('now'), datetime('now')),
  ('std-oral-histories', 'fragmented-oral-histories-spatial-memory', 'col-chinatown-studies', 'Fragmented Oral Histories & Spatial Memory', 'Benevolent associations, boarding houses, and acoustic memories', 'Cataloging spatial memories of benevolent family associations (公所) and rooftop gardens. Mapping unrecorded community institutions through interview fragments.', '2024.06.09', 6, datetime('now'), datetime('now'));
