-- Migration 0004: Seed Initial Content for Threads, Entries, and Relationships
-- Non-destructive inserts using INSERT OR IGNORE

-- 1. Threads
INSERT OR IGNORE INTO threads (id, slug, name, description, order_index, created_at, updated_at)
VALUES
  ('thread-archive', 'archive', 'Archive', 'Taxonomies, institutional custody, and digital permanence.', 1, datetime('now'), datetime('now')),
  ('thread-memory', 'memory', 'Memory', 'Traces of past spaces, collective recollection, and temporal decay.', 2, datetime('now'), datetime('now')),
  ('thread-info-arch', 'information-architecture', 'Information Architecture', 'Structural categorization, schematics, and relational data layers.', 3, datetime('now'), datetime('now')),
  ('thread-spatial', 'spatial-typology', 'Spatial Typology', 'Built environments, cartographic records, and urban thresholds.', 4, datetime('now'), datetime('now')),
  ('thread-heritage', 'heritage', 'Heritage', 'Diaspora identities, inherited languages, and vernacular traditions.', 5, datetime('now'), datetime('now')),
  ('thread-art-history', 'art-history', 'Art History', 'Material culture, historical precedents, and visual semiotics.', 6, datetime('now'), datetime('now')),
  ('thread-governance', 'governance', 'Governance', 'Institutional authority, boundary demarcation, and structural control.', 7, datetime('now'), datetime('now'));

-- 2. Entries (Laboratory Hierarchy: Study -> Entry)
INSERT OR IGNORE INTO entries (id, slug, entry_number, study_id, title, rui_revision, summary, location, archival_date, published_date, last_modified_date, blocks, visibility, order_index, created_at, updated_at)
VALUES
  ('entry-014', 'entry-014-epistemic-armatures', '014', 'std-metadata-labels', 'Epistemic Armatures: Standardizing the Ineffable', 'REV 01', 'A critical note on why metadata frameworks must operate as rigid scaffolds surrounding intentionally variable internal notebook material.', 'San Francisco, CA', '2026.08.03', '2026.08.03', '2026.08.10', '[{"type":"paragraph","content":"When we attempt to catalog an evolving thought, the primary danger is premature over-structuring. An archival system that forces all human observations into identical pre-configured form fields invariably destroys the idiosyncratic nuance of the record itself."},{"type":"observation","date":"2026.08.03 — 14:20 PST","coordinates":"37.7749° N, 122.4194° W","text":"The archive must not be a database masquerading as an art piece; it must be an art practice that adopts the clinical sobriety of the database to resist contemporary social feed ephemerality."},{"type":"image","url":"https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1200&q=80","caption":"Fig 1.1 — Photographic record of catalog card indexing schemas, Special Collections archive study.","alt":"Archival library cards in wooden drawer","scanInfo":"35mm optical capture, archival paper matte scan"},{"type":"fragment","note":"“The inventory is never neutral; to label a fragment is already to decide where in history it is permitted to rest.”","source":"Laboratory Notebook 04, p. 89"},{"type":"paragraph","content":"By establishing a rigid, immutable metadata framework (Collection, Study, Entry, Revision, Coordinates, Threads), the internal notebook body can remain radically free. It may hold a single solitary sentence, twenty uncompressed field rubbings, an excerpt of dialogue, or an exhaustive bibliographic trace."},{"type":"reference","citation":"Bowker, Geoffrey C., and Susan Leigh Star. Sorting Things Out: Classification and Its Consequences. MIT Press, 1999.","link":"https://mitpress.mit.edu/9780262522953/sorting-things-out/","year":"1999"}]', 'published', 1, datetime('now'), datetime('now')),
  ('entry-013', 'entry-013-the-istrian-threshold', '013', 'std-venetian-cartography', 'The Istrian Threshold: Submerged Watermarks', 'REV 00', 'Observations on high-tide algae marks etched into dense limestone along the Fondamenta Nani canal steps.', 'Venice (Dorsoduro)', '2026.07.29', '2026.07.29', '2026.07.29', '[{"type":"paragraph","content":"Istrian stone (pietra d’Istria) possesses an almost metallic impermeability. Unlike soft brick or volcanic tufa, it resists saltwater salt-weathering for centuries. Yet when observed at the lowest tide of the summer syzygy, a permanent dark green tide-mark is visible precisely 42 centimeters above the foundation piles."},{"type":"image","url":"https://images.unsplash.com/photo-1514890547357-a9ee288728e0?auto=format&fit=crop&w=1200&q=80","caption":"Fig 13.1 — Waterline on pietra d’Istria mooring bollard, Rio di San Trovaso.","alt":"Canal water lapping against aged stone steps in Venice","scanInfo":"Medium format analog field capture, summer solstice 2026"},{"type":"list","title":"Field Measurements Recorded (29 July 2026):","items":["High water mark (Acqua Alta spring peak): +118 cm datum","Algae band width: 14.5 cm continuous vertical striation","Chiselled boat-ring erosion: 6 mm depth loss on seaward face","Salinity index at surface: 34.2 PSU"]},{"type":"fragment","note":"The city does not sink so much as the water maintains its slow, deliberate measurement of our transience."}]', 'published', 2, datetime('now'), datetime('now')),
  ('entry-012', 'entry-012-calligraphic-storefront-facades', '012', 'std-vernacular-signs', 'Calligraphic Storefront Facades on Mott Street', 'REV 02', 'Typographic analysis of hand-painted Northern Wei (北魏) style brush characters cast in relief on 1960s commercial building cornices.', 'New York (Manhattan Chinatown)', '2026.07.07', '2026.07.07', '2026.07.22', '[{"type":"paragraph","content":"The Northern Wei script (Beiwei Kaishu), characterized by sharp angular terminals and heavy downward right strokes, was favored by mid-century sign-writers in Hong Kong and subsequently exported to New York and San Francisco Chinatown storefronts. The chisel-like stroke energy gave the merchant names an air of unyielding permanence."},{"type":"image","url":"https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80","caption":"Fig 12.1 — Northern Wei calligraphic signboard fragment, photographed on Mott St.","alt":"Atmospheric street scene in historical Chinatown alley","scanInfo":"35mm field documentation, archival negative #NY-26-088"},{"type":"fragment","note":"Notice how the stroke ‘磔’ (zhe) terminates not in a smooth curve, but in an abrupt, knife-edge drop that mirrors lapidary stone-carving techniques of the 5th century."},{"type":"paragraph","content":"When modernized neon tubes or vinyl wraps replace these timber and brass relief characters, the linguistic lineage collapses from a three-dimensional spatial anchor to a flat promotional sticker."}]', 'published', 3, datetime('now'), datetime('now')),
  ('entry-011', 'entry-011-revision-telemetry-and-human-intent', '011', 'std-revision-systems', 'Revision Telemetry vs. Artistic Intent', 'REV 00', 'Why automatic git hashes or timestamp churn do not constitute genuine revisions in an intellectual body of work.', 'Los Angeles, CA', '2026.06.18', '2026.06.18', '2026.06.18', '[{"type":"paragraph","content":"Modern software infrastructure records every keystroke, file save, and deployment checksum. This provides telemetry, but not curation. A typo correction or layout refactoring is not a philosophical state change."},{"type":"observation","date":"2026.06.18","text":"RUI Revision (e.g. REV 00 → REV 01) is an intentional, deliberate declaration by the creator that the intellectual thesis has mutated or matured."},{"type":"reference","citation":"Benjamin, Walter. “The Work of Art in the Age of Mechanical Reproduction.” Illuminations, edited by Hannah Arendt, Schocken Books, 1969."}]', 'published', 4, datetime('now'), datetime('now')),
  ('entry-010', 'entry-010-trajan-inscriptions-and-surface-spalling', '010', 'std-stone-typography', 'Trajan Inscriptions and Surface Spalling', 'REV 01', 'Field rubbings and optical comparisons of Imperial serif proportions against post-war sulfur dioxide spalling.', 'Rome (Forum Boarium)', '2026.05.14', '2026.05.14', '2026.06.02', '[{"type":"paragraph","content":"Examining the marble pediment dedication near Santa Maria in Cosmedin. The v-cut angle of the letter ‘M’ was originally carved at precisely 48 degrees to catch the low Roman afternoon sunlight. Today, atmospheric gypsum formation has softened the stroke vertex by nearly 3.2 millimeters."},{"type":"image","url":"https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1200&q=80","caption":"Fig 10.1 — Classical Roman stone inscription with ambient shadow angle, Forum Boarium.","alt":"Ancient Roman stone carving with Latin lettering","scanInfo":"High-resolution surface capture, raking daylight 17:30 CET"},{"type":"fragment","note":"“The shadow cast by the incised chisel groove is the true letter; the marble itself is merely the canvas that receives the void.”"}]', 'published', 5, datetime('now'), datetime('now')),
  ('entry-009', 'entry-009-acoustic-resonance-of-clan-halls', '009', 'std-oral-histories', 'Acoustic Resonance of Benevolent Clan Halls', 'REV 00', 'A brief note on the acoustic separation between crowded commercial streets and third-floor family association rooms.', 'San Francisco (Waverly Place)', '2026.04.28', '2026.04.28', '2026.04.28', '[{"type":"paragraph","content":"Stepping off Waverly Place through a narrow, unvarnished wooden stairwell leads up to the altar room of the Ning Yung Association. The acoustic transition is startling: street traffic drops by over 28 decibels, replaced by the faint hum of ceiling fans and the rhythmic click of teakwood tiles."},{"type":"fragment","note":"Spatial sanctuary was constructed vertically in Chinatown rather than horizontally, shielding collective memory inside upper floors beyond street view."}]', 'published', 6, datetime('now'), datetime('now')),
  ('entry-008', 'entry-008-barbari-woodcut-aerial-grid', '008', 'std-venetian-cartography', 'Jacopo de’ Barbari’s Woodcut: The Fiction of Total Vision', 'REV 01', 'Deconstructing the multi-perspective bird’s-eye perspective executed across six pearwood blocks in 1500.', 'Venice (Museo Correr)', '2026.03.15', '2026.03.15', '2026.04.10', '[{"type":"paragraph","content":"Jacopo de’ Barbari had no airplane, no hot air balloon, and no elevated vantage point capable of viewing the Venetian lagoon in its entirety. The monumental 1500 woodcut is an act of speculative synthesis—combining hundreds of ground-level trigonometric compass surveys into a unified god’s-eye projection."},{"type":"image","url":"https://images.unsplash.com/photo-1520175480921-4edfa2983e0f?auto=format&fit=crop&w=1200&q=80","caption":"Fig 8.1 — Aerial canal geometry and lagoon water corridors, Venice.","alt":"Venice canal view from above","scanInfo":"Cartographic reference plate IV"},{"type":"paragraph","content":"In this sense, Barbari’s map is identical to a modern relational database: a structured illusion of omniscience built from thousands of humble, localized data points."}]', 'published', 7, datetime('now'), datetime('now')),
  ('entry-007', 'entry-007-the-death-of-ephemeral-hyperlinks', '007', 'std-metadata-labels', 'Link Rot and the Fragility of Ephemeral Pointers', 'REV 00', 'A technical note on why external URL references must be paired with self-contained plaintext citations in archival records.', 'Los Angeles, CA', '2026.02.04', '2026.02.04', '2026.02.04', '[{"type":"paragraph","content":"Studies of legal scholarship and academic references demonstrate that more than 49% of hyperlinks cited in Supreme Court decisions since 1996 no longer resolve. The hyperlink is a promise that web servers routinely break."},{"type":"fragment","note":"An archive that relies solely on URLs is an archive built on shifting sand. We must always preserve the textual payload itself."}]', 'published', 8, datetime('now'), datetime('now')),
  ('entry-006', 'entry-006-berlin-palimpsest-bullet-scars', '006', 'std-stone-typography', 'Berlin Palimpsest: Shrapnel Patches on Sandstone Columns', 'REV 00', 'Documenting the Neues Museum restoration philosophy by David Chipperfield—preserving war scars in stone rather than grinding them away.', 'Berlin (Museumsinsel)', '2026.01.19', '2026.01.19', '2026.01.19', '[{"type":"paragraph","content":"The fluted columns of the Neues Museum on Berlin’s Museumsinsel are pitted with 1945 bullet impacts. When restored, the conservation team filled only structural voids with pale lime-mortar, leaving the shrapnel cavities visible as negative relief."},{"type":"image","url":"https://images.unsplash.com/photo-1560969184-10fe8719e047?auto=format&fit=crop&w=1200&q=80","caption":"Fig 6.1 — Sandstone architectural facade with preserved historical texture, Berlin.","alt":"Classical museum columns in Berlin","scanInfo":"Architectural documentation scan #BER-26-01"},{"type":"fragment","note":"“Restoration that erases trauma is not preservation; it is architectural amnesia.”"}]', 'published', 9, datetime('now'), datetime('now')),
  ('entry-005', 'entry-005-san-francisco-bilingual-street-blades', '005', 'std-vernacular-signs', 'San Francisco Bilingual Street Blades: Font Incongruity', 'REV 00', 'Observations on municipal metal signs pairing Highway Gothic with generic Ming/SimSun typeface outputs.', 'San Francisco (Grant & California)', '2025.11.10', '2025.11.10', '2025.11.10', '[{"type":"paragraph","content":"In 1970, the City of San Francisco introduced bilingual street signs in Chinatown. While the English names were rendered in federally standardized Highway Gothic (Series E), the Chinese characters were sourced from rudimentary early digital fonts, creating a stark visual clash between civic engineering and mechanical typesetting."},{"type":"fragment","note":"Linguistic governance made visible through contrasting typographic weights on a single green metal blade."}]', 'published', 10, datetime('now'), datetime('now')),
  ('entry-004', 'entry-004-metadata-labels-first-principles', '004', 'std-metadata-labels', 'Metadata Labels: The Grammar of Archival Indexing', 'REV 00', 'Establishing the core fields for ruigallery.xyz: Collection, Study, Entry, Revision, Created, Location, Threads.', 'Los Angeles, CA', '2025.07.07', '2025.07.07', '2025.07.07', '[{"type":"paragraph","content":"To construct an archive that endures beyond changes in web frameworks and CSS libraries, its metadata schema must be strictly formalized. We define seven fundamental properties that accompany every entry regardless of its internal visual composition."},{"type":"list","title":"Rigid Metadata Armature:","items":["COLLECTION — Primary thematic inquiry / period context","STUDY — Longitudinal sub-topic of research","ENTRY — Sequential chronologic identifier","REVISION — Explicit intellectual milestone (REV 00+)","CREATED — ISO chronological anchor","LOCATION — Spatial origin of the observation","THREADS — Horizontal cross-cutting conceptual tags"]},{"type":"fragment","note":"Metadata is rigid; notebook content is flexible. This is the cornerstone principle of RUI."}]', 'published', 11, datetime('now'), datetime('now')),
  ('entry-003', 'entry-003-lisbon-azulejo-fractures', '003', 'std-stone-typography', 'Lisbon Azulejos: Grid Distortion on Alfama Incline', 'REV 00', 'Field survey of glazed ceramic tiles warping along steep 18% hillside street gradients.', 'Lisbon (Alfama)', '2025.05.02', '2025.05.02', '2025.05.02', '[{"type":"paragraph","content":"In Alfama, the geometric cobalt-blue azulejo tile grids encounter the natural, irregular incline of the hillside. Rather than cut tiles obliquely, 19th-century builders staggered the rows in stepped intervals, producing an optical moiré vibration when walking uphill."},{"type":"fragment","note":"Ceramic geometry forced to negotiate topography."}]', 'published', 12, datetime('now'), datetime('now')),
  ('entry-002', 'entry-002-manhattan-chinatown-paper-flyers', '002', 'std-oral-histories', 'Ephemeral Notices on Eldridge Street Lamp Posts', 'REV 00', 'Photographic documentation of layers of pink and yellow employment/apartment flyers glued over cast iron lampposts.', 'New York (Eldridge St)', '2025.03.11', '2025.03.11', '2025.03.11', '[{"type":"paragraph","content":"The street lamp on Eldridge and Division acts as a localized, non-digital bulletin board. Layers of wheatpaste and rice glue have created a paper crust over 1.5 cm thick, encapsulating twenty years of micro-transactions, room rentals, and bus schedules."},{"type":"fragment","note":"An accidental archeology in newsprint and starch."}]', 'published', 13, datetime('now'), datetime('now')),
  ('entry-001', 'entry-001-inaugural-laboratory-manifesto', '001', 'std-metadata-labels', 'Inaugural Laboratory Thesis: Archive Before Complexity', 'REV 00', 'The founding statement establishing ruigallery.xyz as an ongoing artistic, archival, and intellectual laboratory.', 'San Francisco, CA', '2025.01.01', '2025.01.01', '2025.01.01', '[{"type":"paragraph","content":"We begin from a state of total clarity: the website is not an ornament; it is a repository and viewing lens for an evolving archive. We separate finished work (Curated Works) from unfinished inquiries (Laboratory), yet grant both equal intellectual dignity."},{"type":"observation","date":"2025.01.01","text":"Let the visual language reflect ink on paper, high-contrast typography, mathematical spacing, and absolute negative space. We reject disposable social timelines in favor of durable archival chronology."}]', 'published', 14, datetime('now'), datetime('now'));

-- 3. Entry Threads Junction (Many-to-Many)
INSERT OR IGNORE INTO entry_threads (entry_id, thread_id, created_at)
VALUES
  ('entry-014', 'thread-archive', datetime('now')),
  ('entry-014', 'thread-info-arch', datetime('now')),
  ('entry-014', 'thread-governance', datetime('now')),
  ('entry-013', 'thread-spatial', datetime('now')),
  ('entry-013', 'thread-memory', datetime('now')),
  ('entry-012', 'thread-heritage', datetime('now')),
  ('entry-012', 'thread-art-history', datetime('now')),
  ('entry-012', 'thread-spatial', datetime('now')),
  ('entry-011', 'thread-archive', datetime('now')),
  ('entry-011', 'thread-governance', datetime('now')),
  ('entry-010', 'thread-art-history', datetime('now')),
  ('entry-010', 'thread-memory', datetime('now')),
  ('entry-010', 'thread-spatial', datetime('now')),
  ('entry-009', 'thread-heritage', datetime('now')),
  ('entry-009', 'thread-memory', datetime('now')),
  ('entry-009', 'thread-spatial', datetime('now')),
  ('entry-008', 'thread-spatial', datetime('now')),
  ('entry-008', 'thread-art-history', datetime('now')),
  ('entry-008', 'thread-info-arch', datetime('now')),
  ('entry-007', 'thread-archive', datetime('now')),
  ('entry-007', 'thread-governance', datetime('now')),
  ('entry-006', 'thread-memory', datetime('now')),
  ('entry-006', 'thread-art-history', datetime('now')),
  ('entry-006', 'thread-spatial', datetime('now')),
  ('entry-005', 'thread-heritage', datetime('now')),
  ('entry-005', 'thread-spatial', datetime('now')),
  ('entry-005', 'thread-governance', datetime('now')),
  ('entry-004', 'thread-info-arch', datetime('now')),
  ('entry-004', 'thread-archive', datetime('now')),
  ('entry-004', 'thread-memory', datetime('now')),
  ('entry-003', 'thread-spatial', datetime('now')),
  ('entry-003', 'thread-art-history', datetime('now')),
  ('entry-002', 'thread-heritage', datetime('now')),
  ('entry-002', 'thread-memory', datetime('now')),
  ('entry-001', 'thread-archive', datetime('now')),
  ('entry-001', 'thread-info-arch', datetime('now')),
  ('entry-001', 'thread-memory', datetime('now'));

-- 4. Entry Related Studies Junction (Normalized)
INSERT OR IGNORE INTO entry_related_studies (entry_id, study_id, created_at)
VALUES
  ('entry-014', 'std-revision-systems', datetime('now')),
  ('entry-013', 'std-stone-typography', datetime('now')),
  ('entry-012', 'std-oral-histories', datetime('now')),
  ('entry-011', 'std-metadata-labels', datetime('now')),
  ('entry-010', 'std-venetian-cartography', datetime('now')),
  ('entry-009', 'std-vernacular-signs', datetime('now')),
  ('entry-008', 'std-metadata-labels', datetime('now')),
  ('entry-007', 'std-revision-systems', datetime('now')),
  ('entry-006', 'std-stone-typography', datetime('now')),
  ('entry-005', 'std-oral-histories', datetime('now')),
  ('entry-004', 'std-revision-systems', datetime('now')),
  ('entry-003', 'std-stone-typography', datetime('now')),
  ('entry-002', 'std-vernacular-signs', datetime('now')),
  ('entry-001', 'std-revision-systems', datetime('now'));
