-- Migration 0006: Seed Initial Content for Curated Works and Normalized Relationships
-- Non-destructive inserts using INSERT OR IGNORE

-- 1. Curated Works
INSERT OR IGNORE INTO curated_works (
  id, slug, title, subtitle, work_type, year, date, featured_on_home,
  home_layout_weight, cover_image, excerpt, body_blocks, metadata, visibility, order_index, created_at, updated_at
)
VALUES
  ('work-arch-forgetting', 'the-architecture-of-forgetting', 'The Architecture of Forgetting', 'On digital erasure, server obsolescence, and the long archive', 'Essay', '2026', 'August 2026', 1, 'dominant', 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=1600&q=85', 'An inquiry into the systemic decay of contemporary digital media, proposing an ink-on-paper archival methodology to counter the ephemeral amnesia of algorithmic platforms.', '[{"type":"text","content":"We live in the most documented era in human history, yet we occupy the most fragile. While stone inscriptions from Mesopotamia retain their sharp cuneiform ridges four millennia later, digital documents produced in 1998 are already unreadable on modern operating systems without emulation layers."},{"type":"pullquote","quote":"The digital file is not an object; it is an ongoing performance that requires an entire civilization of energy, silicon, and software compatibility to remain legible.","attribution":"RUI, The Architecture of Forgetting (2026)"},{"type":"image","url":"https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1400&q=85","caption":"Plate I — Card index drawer array, Special Collections research archive.","fullWidth":true},{"type":"text","content":"When we build digital archives, our design instinct is often to mimic dynamic dashboards: animated feeds, infinite scrolls, and algorithmic recommendations. Yet these very interaction paradigms are designed for rapid consumption and disposal rather than enduring contemplation. To construct a true archive is to enforce stillness."},{"type":"two_column_images","url1":"https://images.unsplash.com/photo-1507842229451-9f01ab79c4a5?auto=format&fit=crop&w=1000&q=80","caption1":"Plate II.a — Cataloging card detail, ink stamp index.","url2":"https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=1000&q=80","caption2":"Plate II.b — Archival binding study, exposed linen stitch."},{"type":"text","content":"In RUI, we propose a strict architectural separation: application code may change, web frameworks may be superseded, but the core data records—structured by rigid metadata armatures—must remain portable, clinical, and human-readable in plain text for decades to come."}]', '{"medium":"Critical Essay & Archival Prints","readingTime":"12 min read","location":"San Francisco / Los Angeles","edition":"Printed in Monotype Bembo on 120gsm Zerkall mould-made paper"}', 'published', 1, datetime('now'), datetime('now')),
  ('work-stone-salt', 'stone-salt-and-stone-venetian-thresholds', 'Stone, Salt, and Stone', 'Venetian ephemeral thresholds along the Rio di San Trovaso', 'Photography', '2025', 'October 2025', 1, 'horizontal-wide', 'https://images.unsplash.com/photo-1514890547357-a9ee288728e0?auto=format&fit=crop&w=1600&q=85', 'A twelve-plate medium format photographic series surveying Istrian limestone mooring bollards and submerged waterlines in the Dorsoduro district.', '[{"type":"text","content":"Photographed during the extreme low tides of the autumnal equinox, this photographic suite records the submerged foundations of 16th-century palazzi along the Rio di San Trovaso. At the water line, stone ceases to be an architectural support and becomes a geological timeline of algae blooms, mineral deposits, and salt crystallizations."},{"type":"image","url":"https://images.unsplash.com/photo-1534113414509-0eec2bfb493f?auto=format&fit=crop&w=1400&q=85","caption":"Plate 03 — Fondamenta Nani canal steps at minus tide, Istrian stone threshold.","fullWidth":true},{"type":"text","content":"Each image was printed by hand on warm-tone fiber-base paper, processed with selenium toning to ensure chemical longevity matching the stone it depicts."},{"type":"two_column_images","url1":"https://images.unsplash.com/photo-1520175480921-4edfa2983e0f?auto=format&fit=crop&w=1000&q=80","caption1":"Plate 07 — Canal mooring bollard with chiselled iron ring.","url2":"https://images.unsplash.com/photo-1498307833015-e7b400441eb8?auto=format&fit=crop&w=1000&q=80","caption2":"Plate 09 — Ponte dell’Accademia timber pile weathering."}]', '{"medium":"Silver Gelatin Prints from 6x7 Negatives","dimensions":"50 × 60 cm (framed)","edition":"Edition of 5 + 2 AP","location":"Venice, Italy"}', 'published', 2, datetime('now'), datetime('now')),
  ('work-cartographic-palimpsest', 'cartographic-palimpsest-chinatown-typographies', 'Cartographic Palimpsest No. 4', 'Typographies of Chinatown across three generations of migration', 'Visual Work', '2025', 'May 2025', 1, 'standard', 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1600&q=85', 'Silkscreen and letterpress cartographic print exploring the layering of traditional Cantonese signage, neon armatures, and modern municipal typography.', '[{"type":"text","content":"By overlaying 1930 Sanborn fire insurance maps with contemporary high-resolution vector tracings of calligraphic signage along Mott and Pell Streets, Cartographic Palimpsest No. 4 maps the micro-geography of family association headquarters and merchant guilds."},{"type":"image","url":"https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1400&q=85","caption":"Plate I — Layered proof print, Chinese calligraphy overlaid on street grid coordinates.","fullWidth":true},{"type":"pullquote","quote":"The street name is not merely a postal address; it is a linguistic palimpsest where ancestral dialect terms survive beneath English phonetics.","attribution":"Exhibition catalog text, Asian American Art Center"}]', '{"medium":"4-color Silkscreen & Hand-Set Metal Type on Mulberry Paper","dimensions":"76 × 102 cm","edition":"Numbered edition of 25","location":"New York & San Francisco"}', 'published', 3, datetime('now'), datetime('now')),
  ('work-optical-scans', 'instruments-of-observation-optical-scans', 'Instruments of Observation', 'Optical scans, contact rubbings, and epistemic traces', 'Mixed Media', '2024', 'November 2024', 1, 'editorial-compact', 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1600&q=85', 'A spatial laboratory installation combining charcoal paper rubbings of Roman inscriptions with digital scanning instruments.', '[{"type":"text","content":"Installed in a darkened gallery space, Instruments of Observation pairs direct physical contact impressions (charcoal rubbings on Japanese kozo paper) with modern non-contact laser profilometry of the same marble surfaces."},{"type":"image","url":"https://images.unsplash.com/photo-1560969184-10fe8719e047?auto=format&fit=crop&w=1400&q=85","caption":"Installation view — Berlin studio study.","fullWidth":true}]', '{"medium":"Graphite rubbings, optical sensor output, aluminum framing","dimensions":"Variable installation dimensions","location":"Rome & Berlin"}', 'published', 4, datetime('now'), datetime('now'));

-- 2. Curated Work Related Studies (Junction)
INSERT OR IGNORE INTO curated_work_related_studies (work_id, study_id, created_at)
VALUES
  ('work-arch-forgetting', 'std-metadata-labels', datetime('now')),
  ('work-arch-forgetting', 'std-revision-systems', datetime('now')),
  ('work-stone-salt', 'std-venetian-cartography', datetime('now')),
  ('work-stone-salt', 'std-stone-typography', datetime('now')),
  ('work-cartographic-palimpsest', 'std-vernacular-signs', datetime('now')),
  ('work-cartographic-palimpsest', 'std-oral-histories', datetime('now')),
  ('work-optical-scans', 'std-stone-typography', datetime('now'));

-- 3. Curated Work Related Entries (Junction)
INSERT OR IGNORE INTO curated_work_related_entries (work_id, entry_id, created_at)
VALUES
  ('work-arch-forgetting', 'entry-014', datetime('now')),
  ('work-arch-forgetting', 'entry-007', datetime('now')),
  ('work-stone-salt', 'entry-013', datetime('now')),
  ('work-stone-salt', 'entry-008', datetime('now')),
  ('work-cartographic-palimpsest', 'entry-012', datetime('now')),
  ('work-cartographic-palimpsest', 'entry-005', datetime('now')),
  ('work-optical-scans', 'entry-010', datetime('now')),
  ('work-optical-scans', 'entry-006', datetime('now'));
